server:
    port: 8091
spring:
    application:
        name: item-service
    datasource:
        url: jdbc:mysql://localhost:3307/wlkg
        username: root
        password: root
        hikari:
            maximum-pool-size: 30
            minimum-idle: 10
    rabbitmq:       #添加一些有关RabbitMQ的配置
        host: 10.11.60.234
        username: wlkg
        password: 123456
        virtual-host: /wlkg
        template:
            retry:
                enabled: true
                initial-interval: 10000ms
                max-interval: 300000ms
                multiplier: 2
            exchange: wlkg.item.exchange
        publisher-confirms: true

        #- template：有关`AmqpTemplate`的配置
          #  - retry：失败重试
          #    - enabled：开启失败重试
          #    - initial-interval：第一次重试的间隔时长
          #    - max-interval：最长重试间隔，超过这个间隔将不再重试
          #    - multiplier：下次重试间隔的倍数，此处是2即下次重试间隔是上次的2倍
        #  - exchange：缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
        #- publisher-confirms：生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true

eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:10086/eureka
    instance:
        lease-renewal-interval-in-seconds: 5 # 每隔 5 秒发送一次心跳
        lease-expiration-duration-in-seconds: 10 # 10 秒不发送就过期
        prefer-ip-address: true
        ip-address: 127.0.0.1
        instance-id: ${spring.application.name}:${server.port}
zuul:
    prefix: /api # 添加路由前缀
    retryable: true
    routes:
        item-service: /item/** # 将商品微服务映射到/item/**