server:
  port: 8096
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/wlkg
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:      #添加RabbitMQ和Redis配置：
    host: 10.11.60.234
  rabbitmq:
    host: 10.11.60.234
    username: wlkg
    password: 123456
    virtual-host: /wlkg
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 210000ms
        multiplier: 2
    publisher-confirms: true


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: com.wlkg.pojo      #指定POJO扫描包来让mybatis自动扫描到自定义POJO